export type KnowledgeSource = {
  type: 'file' | 'url' | 'text';
  name: string; // Filename, URL, or descriptive name for text
  status?: 'processing' | 'ready' | 'error'; // Optional: Tracking status
  path?: string; // Optional: Server-side file path for uploaded files
  chunks?: string[]; // Optional: Array of text chunks
};

export type AgentSettings = {
  createCards: boolean;
  linkedPipelineId: string | null;
  initialMessages: string[];
  suggestedReplies: string[];
  primaryColor: string;
};

export type AgentConfiguration = {
  id: string; // Unique ID generated by the backend
  userId: string; // To associate with a user (placeholder)
  name: string;
  systemPrompt: string;
  knowledgeSources: KnowledgeSource[];
  settings: AgentSettings;
  status: 'Active' | 'Inactive' | 'Training'; // Agent's operational status
  createdAt: string; // ISO Date string
  updatedAt: string; // ISO Date string
}; 