import { Metadata } from 'next';

// Metadata generation function for proposal pages
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const resolvedParams = await params;
  
  return {
    title: `Proposal ${resolvedParams.id} | Deliver AI`,
    description: 'View a saved proposal generated by the Contextual Deal Writer',
  };
} 